name: asterix
description: Asterix app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_screenutil: ^1.0.2
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_statusbarcolor: ^0.2.3
  http: ^0.12.0+4
  community_material_icon: ^3.5.95
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_dotenv: ^2.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500

  assets:
    - assets/
    - .env

